### PR TITLE
leptos::server?

### PR DESCRIPTION
**Pull request by sjud**
if leptos::server pub exports leptos_spin_macro then this will work.

### CODE REVIEW

**Comment by diversable** [comment]
> if leptos::server pub exports leptos_spin_macro then this will work.

Good idea to simplify the exports.. 

I'm still getting some build failures from the updated template when building with `cargo-generate --path ./start-spin` then `spin build --up` in the generated project with the latest PR though.. 

@sjud - do you have time to tackle these errors, or do you want me to pick up the thread from here? I know working with templates can be a pain..


image

**Comment by sjud** [comment]
> @sjud - do you have time to tackle these errors, or do you want me to pick up the thread from here? I know working with templates can be a pain..

Can you pick it up? I'm not sure what's going on here. :)

**Comment by sjud** [comment]
> I'm still getting some build failures from the updated template when building with cargo-generate --path ./start-spin then spin build --up in the generated project with the latest PR though..

Can you pick it up? I'm not sure what's going on, sorry!

**Comment by diversable** [comment]
> Can you pick it up? I'm not sure what's going on, sorry!

Will do - thanks for your work on this!

**Pull request merged**
